# Generated by Django 5.2.3 on 2025-07-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('item1', models.CharField(max_length=50)),
                ('item2', models.CharField(max_length=50)),
                ('item3', models.CharField(max_length=50)),
                ('item4', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Services',
                'verbose_name_plural': 'Services',
                'db_table': 'Services',
                'managed': True,
            },
        ),
    ]
