# Generated by Django 5.2.3 on 2025-07-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0002_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg', models.TextField()),
                ('title', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'ChooseUs',
                'verbose_name_plural': 'ChooseUs',
                'db_table': 'ChooseUs',
                'managed': True,
            },
        ),
    ]
