# Generated by Django 5.2.3 on 2025-07-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0003_chooseus'),
    ]

    operations = [
        migrations.AddField(
            model_name='chooseus',
            name='delay',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
