# Generated by Django 5.2.3 on 2025-07-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0004_chooseus_delay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('delay', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'db_table': 'Testimonial',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='chooseus',
            name='delay',
            field=models.CharField(max_length=50),
        ),
    ]
