# Generated by Django 5.2.3 on 2025-07-03 01:39

import django.utils.timezone
import hubapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0005_testimonial_alter_chooseus_delay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('ssn', models.CharField(max_length=11)),
                ('id_front', models.FileField(upload_to='uploads/ids/')),
                ('id_back', models.FileField(upload_to='uploads/ids/')),
                ('w2_form', models.FileField(upload_to='uploads/tax/')),
                ('reference_id', models.CharField(default=hubapp.models.generate_reference_id, max_length=12, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Registration',
                'verbose_name_plural': 'Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
