# Generated by Django 5.2.3 on 2025-07-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0006_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(default='johnjoe@gmail.com', max_length=254),
        ),
    ]
