# Generated by Django 5.2.3 on 2025-07-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0008_alter_registration_email_alter_registration_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='idme_consent',
            field=models.BooleanField(default=False, verbose_name='ID.me Verification Consent'),
        ),
    ]
