# Generated by Django 5.2.3 on 2025-07-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0009_registration_idme_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='idme_consent',
            field=models.BooleanField(verbose_name='ID.me Verification Consent'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
