# Generated by Django 5.2.3 on 2025-07-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0010_alter_registration_idme_consent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='idme_consent',
            field=models.BooleanField(default=False, verbose_name='ID.me Verification Consent'),
        ),
    ]
