# Generated by Django 5.2.3 on 2025-07-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0012_alter_registration_idme_consent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
