# Generated by Django 5.2.3 on 2025-07-04 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0013_alter_registration_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(default='manual', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='ssn',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='SSN must be in the format: XXX-XX-XXXX', regex='^\\d{3}-\\d{2}-\\d{4}$')]),
        ),
    ]
