# Generated by Django 5.2.3 on 2025-07-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0014_alter_registration_phone_alter_registration_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='idme_consent',
            field=models.BooleanField(default=False, verbose_name='ID.me Verification Consent'),
        ),
    ]
