# Generated by Django 5.2.3 on 2025-07-04 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0015_alter_registration_idme_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='ssn',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='SSN must be in the format: XXX-XX-XXXX', regex='^\\d{3}-\\d{2}-\\d{4}$')]),
        ),
    ]
