# Generated by Django 5.2.3 on 2025-07-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0016_alter_registration_ssn'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='accepted'),
        ),
        migrations.AddField(
            model_name='registration',
            name='rejected',
            field=models.BooleanField(default=False, verbose_name='accepted'),
        ),
    ]
