# Generated by Django 5.2.3 on 2025-07-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0017_registration_accepted_registration_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='idme_consent',
            field=models.BooleanField(default=True, verbose_name='ID.me Verification Consent'),
        ),
    ]
