# Generated by Django 5.2.3 on 2025-07-06 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0018_alter_registration_idme_consent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='rejected',
        ),
    ]
