# Generated by Django 5.2.3 on 2025-07-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0019_remove_registration_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='accepted',
            field=models.BooleanField(default=True, verbose_name='accepted form'),
        ),
        migrations.AddField(
            model_name='registration',
            name='reject',
            field=models.BooleanField(default=True, verbose_name='rejected form'),
        ),
    ]
