# Generated by Django 5.2.3 on 2025-07-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0020_registration_accepted_registration_reject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='accepted form'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='reject',
            field=models.BooleanField(default=False, verbose_name='rejected form'),
        ),
    ]
