# Generated by Django 5.2.3 on 2025-07-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0021_alter_registration_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='reject',
        ),
        migrations.AddField(
            model_name='registration',
            name='accept',
            field=models.BooleanField(default=False, verbose_name='accepted '),
        ),
        migrations.AddField(
            model_name='registration',
            name='rejected',
            field=models.BooleanField(default=False, verbose_name='rejected'),
        ),
    ]
