# Generated by Django 5.2.3 on 2025-07-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0022_remove_registration_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='telegram_link',
            field=models.CharField(default='http://t.me/Brokershub1', max_length=80),
        ),
    ]
